### ISSUE TITLE
Region is missing

### ISSUE THREAD

**Issue by PixsaOJ** [bizon/selling-partner-api-sdk#429]
I am trying to `getOrders`

```bash
aws/node_modules/.pnpm/@aws-sdk+config-resolver@3.110.0/node_modules/@aws-sdk/config-resolver/dist-cjs/regionConfig/config.js:10
        throw new Error("Region is missing");

Error: Region is missing
    at default (/aws/node_modules/.pnpm/@aws-sdk+config-resolver@3.110.0/node_modules/@aws-sdk/config-resolver/dist-cjs/regionConfig/config.js:10:15)
    at aws/node_modules/.pnpm/@aws-sdk+node-config-provider@3.110.0/node_modules/@aws-sdk/node-config-provider/dist-cjs/fromStatic.js:6:83
    at /aws/node_modules/.pnpm/@aws-sdk+property-provider@3.110.0/node_modules/@aws-sdk/property-provider/dist-cjs/chain.js:11:28
    at async coalesceProvider (/aws/node_modules/.pnpm/@aws-sdk+property-provider@3.110.0/node_modules/@aws-sdk/property-provider/dist-cjs/memoize.js:14:24)
    at asyncaws/node_modules/.pnpm/@aws-sdk+property-provider@3.110.0/node_modules/@aws-sdk/property-provider/dist-cjs/memoize.js:26:28
    at async Object.region (/aws/node_modules/.pnpm/@aws-sdk+config-resolver@3.110.0/node_modules/@aws-sdk/config-resolver/dist-cjs/regionConfig/resolveRegionConfig.js:17:36)
    at async getEndpointFromRegion (aws/node_modules/.pnpm/@aws-sdk+config-resolver@3.110.0/node_modules/@aws-sdk/config-resolver/dist-cjs/endpointsConfig/utils/getEndpointFromRegion.js:7:20)
    at async buildHttpRpcRequest (aws/node_modules/.pnpm/@aws-sdk+client-sts@3.118.0/node_modules/@aws-sdk/client-sts/dist-cjs/protocols/Aws_query.js:1029:68)
    at async aws/node_modules/.pnpm/@aws-sdk+middleware-serde@3.110.0/node_modules/@aws-sdk/middleware-serde/dist-cjs/serializerMiddleware.js:5:21
    at async aws/node_modules/.pnpm/@aws-sdk+middleware-logger@3.110.0/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22
```

Here is the code:

```javascript
    const auth = new SellingPartnerApiAuth({
      clientId: process.env.LWA_CLIENT_ID,
      clientSecret: process.env.LWA_CLIENT_SECRET,
      refreshToken: process.env.LWA_APP_REFRESH_TOKEN,
      accessKeyId: process.env.AWS_ACCESS_KEY_ID,
      secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
      role: {
        arn: process.env.AWS_SELLING_PARTNER_ROLE,
      },
    })

    const client = new OrdersApiClient({
      auth,
      region: 'na'
    })

    const res = client.getOrders(
      {
        marketplaceIds: ['ATVPDKIKX0DER']
      }
    );
```

**Comment by PixsaOJ** [comment]
I had to add `AWS_DEFAULT_REGION=us-east-1` in my .env file.

**Comment by tusbar** [comment]
Oh my bad `RequireExactlyOne` will indeed force you to specify either `refreshToken` or `scopes`. We’ll update the types accordingly in a next release.

Thanks.
